import { useState, useEffect } from 'react';
import api from '../../services/api';
import { motion } from 'framer-motion';
import { FileDown, Calendar, Users, FolderKanban, CheckCircle2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { format } from 'date-fns';

const AdminReports = () => {
  const [reportData, setReportData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const { data } = await api.get('/admin/report');
        setReportData(data);
      } catch (error) {
        toast.error('Failed to load report data');
      } finally {
        setIsLoading(false);
      }
    };
    fetchReport();
  }, []);

  const handleExportCSV = () => {
    if (!reportData) return;
    const headers = ['Project Name', 'Admin', 'Member Count', 'Total Tasks', 'Completed Tasks', 'Status'];
    const csvContent = [
      headers.join(','),
      ...reportData.projectsData.map(p => [
        `"${p.name}"`,
        `"${p.admin}"`,
        p.memberCount,
        p.taskCount,
        p.completedTasks,
        p.status
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `taskflow_admin_report_${format(new Date(), 'yyyy-MM-dd')}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[70vh]">
        <div className="w-12 h-12 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 print:hidden">
        <div>
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">System Report</h1>
          <p className="text-slate-500 dark:text-slate-400 mt-2 text-lg">Comprehensive breakdown of workspace activity.</p>
        </div>
        <button 
          onClick={handleExportCSV}
          className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-semibold shadow-lg shadow-indigo-500/30 transition-colors"
        >
          <FileDown size={18} />
          Export to CSV
        </button>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white dark:bg-slate-800/80 backdrop-blur-sm rounded-3xl p-8 shadow-sm border border-slate-100 dark:border-slate-700/50 print:p-0 print:shadow-none print:border-none print:bg-transparent"
      >
        <div className="flex justify-between items-center mb-8 pb-6 border-b border-slate-200 dark:border-slate-700 print:border-slate-300">
           <div>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white print:text-black flex items-center gap-2">
                 TaskFlow <span className="text-indigo-600 dark:text-indigo-400 print:text-indigo-600">Analytics Report</span>
              </h2>
              <p className="text-slate-500 print:text-slate-600 mt-1">Generated by {reportData?.generatedBy}</p>
           </div>
           <div className="text-right">
              <div className="flex items-center gap-2 text-slate-500 print:text-slate-600 justify-end">
                <Calendar size={16} />
                <span className="font-medium">{format(new Date(reportData?.generatedAt), 'MMMM d, yyyy')}</span>
              </div>
           </div>
        </div>

        <div className="grid grid-cols-3 gap-6 mb-10">
          <div className="bg-slate-50 dark:bg-slate-800 print:bg-slate-50 p-6 rounded-2xl border border-slate-100 dark:border-slate-700 print:border-slate-200">
            <div className="flex items-center gap-3 text-indigo-600 dark:text-indigo-400 print:text-indigo-600 mb-2">
              <Users size={20} />
              <span className="font-bold uppercase tracking-wider text-xs">Total Users</span>
            </div>
            <p className="text-3xl font-extrabold text-slate-900 dark:text-white print:text-black">{reportData?.summary.totalUsers}</p>
          </div>
          <div className="bg-slate-50 dark:bg-slate-800 print:bg-slate-50 p-6 rounded-2xl border border-slate-100 dark:border-slate-700 print:border-slate-200">
            <div className="flex items-center gap-3 text-violet-600 dark:text-violet-400 print:text-violet-600 mb-2">
              <FolderKanban size={20} />
              <span className="font-bold uppercase tracking-wider text-xs">Total Projects</span>
            </div>
            <p className="text-3xl font-extrabold text-slate-900 dark:text-white print:text-black">{reportData?.summary.totalProjects}</p>
          </div>
          <div className="bg-slate-50 dark:bg-slate-800 print:bg-slate-50 p-6 rounded-2xl border border-slate-100 dark:border-slate-700 print:border-slate-200">
            <div className="flex items-center gap-3 text-emerald-600 dark:text-emerald-400 print:text-emerald-600 mb-2">
              <CheckCircle2 size={20} />
              <span className="font-bold uppercase tracking-wider text-xs">Total Tasks</span>
            </div>
            <p className="text-3xl font-extrabold text-slate-900 dark:text-white print:text-black">{reportData?.summary.totalTasks}</p>
          </div>
        </div>

        <h3 className="text-xl font-bold text-slate-900 dark:text-white print:text-black mb-6">Project Details</h3>
        
        <div className="overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700 print:border-slate-300">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-800 print:bg-slate-100 border-b border-slate-200 dark:border-slate-700 print:border-slate-300">
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700">Project Name</th>
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700">Admin</th>
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700 text-center">Members</th>
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700 text-center">Total Tasks</th>
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700 text-center">Completed</th>
                <th className="p-4 font-bold text-slate-600 dark:text-slate-300 print:text-slate-700">Status</th>
              </tr>
            </thead>
            <tbody>
              {reportData?.projectsData.map((project) => (
                <tr key={project.id} className="border-b border-slate-100 dark:border-slate-700/50 print:border-slate-200 hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors">
                  <td className="p-4 font-semibold text-slate-900 dark:text-white print:text-black">{project.name}</td>
                  <td className="p-4 text-slate-600 dark:text-slate-400 print:text-slate-700">{project.admin}</td>
                  <td className="p-4 text-center font-medium text-slate-900 dark:text-white print:text-black">{project.memberCount}</td>
                  <td className="p-4 text-center font-medium text-slate-900 dark:text-white print:text-black">{project.taskCount}</td>
                  <td className="p-4 text-center font-medium text-emerald-600 dark:text-emerald-400 print:text-emerald-600">{project.completedTasks}</td>
                  <td className="p-4">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                      project.status === 'Active' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-500/20 dark:text-emerald-400 print:border print:border-emerald-500' :
                      project.status === 'Completed' ? 'bg-indigo-100 text-indigo-800 dark:bg-indigo-500/20 dark:text-indigo-400 print:border print:border-indigo-500' :
                      'bg-slate-100 text-slate-800 dark:bg-slate-500/20 dark:text-slate-400 print:border print:border-slate-400'
                    }`}>
                      {project.status}
                    </span>
                  </td>
                </tr>
              ))}
              {reportData?.projectsData.length === 0 && (
                <tr>
                  <td colSpan="6" className="p-8 text-center text-slate-500">No projects found.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </motion.div>
    </div>
  );
};

export default AdminReports;
